import { motion } from "framer-motion";
import { useTranslation } from "react-i18next";

const STEPS = [
  {
    key: "step1" as const,
    num: "01",
    prompt: '"帮我做一个团队成员邀请功能，带邮件通知"',
    promptEn: '"Add a team invitation feature with email notification"',
  },
  {
    key: "step2" as const,
    num: "02",
    code: `// Auto-generated by Claude ✨
export const inviteRouter = router({
  send: protectedProcedure
    .input(InviteInputSchema)
    .output(InviteOutputSchema)
    .mutation(async ({ input, ctx }) => {
      return inviteService.send(input, ctx.userId);
    }),
});`,
  },
  {
    key: "step3" as const,
    num: "03",
    result: "✓ Types inferred · ✓ Lint passed · ✓ PR merged",
  },
] as const;

export function HowItWorks() {
  const { t } = useTranslation();

  return (
    <section
      id="howItWorks"
      className="relative py-24 sm:py-32 bg-zinc-50 dark:bg-zinc-900/50"
    >
      {/* Subtle gradient top */}
      <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-zinc-200 dark:via-zinc-800 to-transparent" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl sm:text-5xl font-extrabold text-zinc-900 dark:text-white tracking-tight">
            {t("landing.howItWorks.sectionTitle")}
          </h2>
          <p className="mt-4 text-lg text-zinc-600 dark:text-zinc-400 max-w-2xl mx-auto">
            {t("landing.howItWorks.sectionSubtitle")}
          </p>
        </motion.div>

        {/* Steps */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 relative">
          {/* Connector line — spans col1 center → col3 center */}
          <div className="hidden lg:block absolute top-5 left-[16.667%] right-[16.667%] h-px bg-gradient-to-r from-blue-300 dark:from-blue-700 to-indigo-300 dark:to-indigo-700" />

          {STEPS.map((step, index) => (
            <motion.div
              key={step.key}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: index * 0.15 }}
              className="relative flex flex-col"
            >
              {/* Step number — centered */}
              <div className="flex justify-center mb-6 relative z-10">
                <div className="w-10 h-10 rounded-full bg-gradient-to-r from-blue-600 to-indigo-600 text-white text-sm font-bold flex items-center justify-center shadow-lg shadow-blue-500/20">
                  {step.num}
                </div>
              </div>

              {/* Card */}
              <div className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 flex-1 shadow-sm text-center">
                <h3 className="text-lg font-semibold text-zinc-900 dark:text-white mb-2">
                  {t(`landing.howItWorks.steps.${step.key}.title`)}
                </h3>
                <p className="text-sm text-zinc-600 dark:text-zinc-400 mb-4 leading-relaxed">
                  {t(`landing.howItWorks.steps.${step.key}.desc`)}
                </p>

                {/* Visual hint for each step */}
                {step.key === "step1" && (
                  <div className="mt-4 rounded-lg bg-zinc-50 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 p-3">
                    <div className="flex items-start gap-2">
                      <span className="text-violet-500 mt-0.5 flex-shrink-0">
                        <svg
                          aria-hidden="true"
                          className="w-4 h-4"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="2"
                        >
                          <path d="M12 2a10 10 0 1 0 10 10A10 10 0 0 0 12 2zm0 4v4l3 3" />
                        </svg>
                      </span>
                      <p className="text-xs text-zinc-500 dark:text-zinc-400 italic">
                        {step.prompt}
                      </p>
                    </div>
                  </div>
                )}

                {step.key === "step2" && (
                  <div className="mt-4 rounded-lg bg-zinc-950 dark:bg-black border border-zinc-800 p-3 overflow-x-auto text-left">
                    <code className="block text-[11px] leading-[1.7] font-mono whitespace-pre">
                      <div>
                        <span style={{ color: "#5c6370", fontStyle: "italic" }}>
                          {"// Auto-generated by Claude ✨"}
                        </span>
                      </div>
                      <div>
                        <span style={{ color: "#c678dd" }}>export</span>{" "}
                        <span style={{ color: "#c678dd" }}>const</span>{" "}
                        <span style={{ color: "#e06c75" }}>inviteRouter</span>
                        <span style={{ color: "#abb2bf" }}>{" = "}</span>
                        <span style={{ color: "#61afef" }}>router</span>
                        <span style={{ color: "#abb2bf" }}>{"({"}</span>
                      </div>
                      <div>
                        <span style={{ color: "#abb2bf" }}>{"  "}</span>
                        <span style={{ color: "#e06c75" }}>send</span>
                        <span style={{ color: "#abb2bf" }}>{": "}</span>
                        <span style={{ color: "#56b6c2" }}>
                          protectedProcedure
                        </span>
                      </div>
                      <div>
                        <span style={{ color: "#abb2bf" }}>{"    ."}</span>
                        <span style={{ color: "#61afef" }}>input</span>
                        <span style={{ color: "#abb2bf" }}>{"("}</span>
                        <span style={{ color: "#e5c07b" }}>
                          InviteInputSchema
                        </span>
                        <span style={{ color: "#abb2bf" }}>{")"}</span>
                      </div>
                      <div>
                        <span style={{ color: "#abb2bf" }}>{"    ."}</span>
                        <span style={{ color: "#61afef" }}>output</span>
                        <span style={{ color: "#abb2bf" }}>{"("}</span>
                        <span style={{ color: "#e5c07b" }}>
                          InviteOutputSchema
                        </span>
                        <span style={{ color: "#abb2bf" }}>{")"}</span>
                      </div>
                      <div>
                        <span style={{ color: "#abb2bf" }}>{"    ."}</span>
                        <span style={{ color: "#61afef" }}>mutation</span>
                        <span style={{ color: "#abb2bf" }}>{"("}</span>
                        <span style={{ color: "#c678dd" }}>async</span>
                        <span style={{ color: "#abb2bf" }}>{" ({ "}</span>
                        <span style={{ color: "#e06c75" }}>input</span>
                        <span style={{ color: "#abb2bf" }}>{", "}</span>
                        <span style={{ color: "#e06c75" }}>ctx</span>
                        <span style={{ color: "#abb2bf" }}>{" }) => {"}</span>
                      </div>
                      <div>
                        <span style={{ color: "#abb2bf" }}>{"      "}</span>
                        <span style={{ color: "#c678dd" }}>return</span>{" "}
                        <span style={{ color: "#56b6c2" }}>inviteService</span>
                        <span style={{ color: "#abb2bf" }}>{"."}</span>
                        <span style={{ color: "#61afef" }}>send</span>
                        <span style={{ color: "#abb2bf" }}>{"("}</span>
                        <span style={{ color: "#e06c75" }}>input</span>
                        <span style={{ color: "#abb2bf" }}>{", "}</span>
                        <span style={{ color: "#e06c75" }}>ctx</span>
                        <span style={{ color: "#abb2bf" }}>{"."}</span>
                        <span style={{ color: "#9cdcfe" }}>userId</span>
                        <span style={{ color: "#abb2bf" }}>{");"}</span>
                      </div>
                      <div>
                        <span style={{ color: "#abb2bf" }}>{"    }),"}</span>
                      </div>
                      <div>
                        <span style={{ color: "#abb2bf" }}>{");"}</span>
                      </div>
                    </code>
                  </div>
                )}

                {step.key === "step3" && (
                  <div className="mt-4 space-y-2">
                    {(["typesInferred", "lintPassed", "prMerged"] as const).map(
                      (itemKey) => (
                        <div
                          key={itemKey}
                          className="flex items-center gap-2 text-xs text-emerald-600 dark:text-emerald-400 font-medium"
                        >
                          <svg
                            aria-hidden="true"
                            className="w-4 h-4 flex-shrink-0"
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth="2.5"
                          >
                            <path
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              d="M5 13l4 4L19 7"
                            />
                          </svg>
                          {t(`landing.howItWorksDemo.${itemKey}`)}
                        </div>
                      ),
                    )}
                  </div>
                )}
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
