// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/unauthorized": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/:workspace": {
    params: {
      "workspace": string;
    };
  };
  "/dashboard/:workspace/:page": {
    params: {
      "workspace": string;
      "page": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/unauthorized" | "/*" | "/dashboard" | "/dashboard/:workspace" | "/dashboard/:workspace/:page";
  };
  "routes/home/route.tsx": {
    id: "routes/home/route";
    page: "/";
  };
  "routes/login/route.tsx": {
    id: "routes/login/route";
    page: "/login";
  };
  "routes/register/route.tsx": {
    id: "routes/register/route";
    page: "/register";
  };
  "routes/unauthorized/route.tsx": {
    id: "routes/unauthorized/route";
    page: "/unauthorized";
  };
  "routes/splat/route.tsx": {
    id: "routes/splat/route";
    page: "/*";
  };
  "routes/dashboard/route.tsx": {
    id: "routes/dashboard/route";
    page: "/dashboard" | "/dashboard/:workspace" | "/dashboard/:workspace/:page";
  };
  "routes/dashboard/_index/route.tsx": {
    id: "routes/dashboard/_index/route";
    page: "/dashboard";
  };
  "routes/dashboard/$workspace/route.tsx": {
    id: "routes/dashboard/$workspace/route";
    page: "/dashboard/:workspace" | "/dashboard/:workspace/:page";
  };
  "routes/dashboard/$workspace/_index/route.tsx": {
    id: "routes/dashboard/$workspace/_index/route";
    page: "/dashboard/:workspace";
  };
  "routes/dashboard/$workspace/$page/route.tsx": {
    id: "routes/dashboard/$workspace/$page/route";
    page: "/dashboard/:workspace/:page";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/home/route": typeof import("./src/routes/home/route.tsx");
  "routes/login/route": typeof import("./src/routes/login/route.tsx");
  "routes/register/route": typeof import("./src/routes/register/route.tsx");
  "routes/unauthorized/route": typeof import("./src/routes/unauthorized/route.tsx");
  "routes/splat/route": typeof import("./src/routes/splat/route.tsx");
  "routes/dashboard/route": typeof import("./src/routes/dashboard/route.tsx");
  "routes/dashboard/_index/route": typeof import("./src/routes/dashboard/_index/route.tsx");
  "routes/dashboard/$workspace/route": typeof import("./src/routes/dashboard/$workspace/route.tsx");
  "routes/dashboard/$workspace/_index/route": typeof import("./src/routes/dashboard/$workspace/_index/route.tsx");
  "routes/dashboard/$workspace/$page/route": typeof import("./src/routes/dashboard/$workspace/$page/route.tsx");
};